# Proxied-installer locale.conf.
#
# Replaces the Calamares installer's locale.conf file.
# The only functional change vs. upstream is that the `geoip:` block is
# removed: geoip.kde.org which may be unreachable behind the Cache proxy.
useSystemTimezone: true

# Isn't supported on NixOS
adjustLiveTimezone: false

localeGenPath: @glibcLocales@/share/i18n/SUPPORTED
